version: '3'

services:
  auth-server:    
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - auth-database
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./app.auth.setting.json:/app/app.auth.setting.json:ro
    ports:
      - 8080:8080
    networks:
      - homemix_net

  auth-database:
    image: postgres:18.1
    container_name: auth-database
    restart: always
    environment:
      POSTGRES_DB: ${DB_PGS_NAME}
      POSTGRES_USER: ${DB_PGS_USERNAME}
      POSTGRES_PASSWORD: ${DB_PGS_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/database:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    expose:
      - '5432'
    networks:
      - homemix_net

networks:
  homemix_net: