version: '3'

services:
  auth-server:    
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - auth-database
    restart: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      SERVER_BASEURL: ${SERVER_BASEURL}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
      AUTH_STORAGE: ${AUTH_STORAGE}
      JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
      JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_LIFETIME: ${COOKIE_LIFETIME}
      DATABASE_ADDRESS: ${DATABASE_ADDRESS}
      REDIS_ADDRESS: ${REDIS_ADDRESS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - 8080:8080
    networks:
      - singleauth_net

  auth-database:
    image: postgres:18.1
    container_name: auth-database
    restart: always
    environment:
      POSTGRES_DB: ${DB_PGS_NAME}
      POSTGRES_USER: ${DB_PGS_USERNAME}
      POSTGRES_PASSWORD: ${DB_PGS_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - '5432'
    networks:
      - singleauth_net

  auth-redis:
    image: redis:latest
    container_name: auth-redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - '6379'
    volumes:
      - ./data/redis/data:/root/redis
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DB}
    networks:
      - singleauth_net

networks:
  singleauth_net: